##  Plugin Information  ##
name: LightLevelBlocker
version: 1.1
main: syam.LightLevelBlocker.LightLevelBlocker
description: LightLevelBlocker Plugin
website: http://sakura-server.net/
##  Original Author     ##
author: syam
permissions:
    llb.bypass:
        default: op
        description: Allow bypass this plugin